pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID = credentials ('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials ('AWS_SECRET_ACCESS_KEY')
    }
    stages {
        
        // get code form repo
        stage ('scm checkout') {
            steps {
                echo 'retrieveing code from github'
                git 'https://github.com/qui3tst0Rm/ScalableWordpressDeploymentOnAWS.git'
                echo 'code retrival complete'
            }
        }

        // initialize configuration files in working directory
        stage ('initialize tf') {
            steps {
                echo 'initializing working directory'
                sh 'terraform init'
                echo 'working directory initialized'
            }
        }

        // run terraform destroy
        stage ('tf destroy') {
            steps {
                echo 'destroying terraform config'
                sh 'terraform destroy -auto-approve'
                echo 'destruction complete'
            }
        }


    }
}
